### ISSUE TITLE
Node rewrite checklist

### ISSUE THREAD

**Issue by aqua-rar** [aqua-rar/Nice-Senpai#20]
## Dab bot
- [x] : $$
- [x] : give
- [x] : leaderboards
- [x] : bet roll
- [x] : bet flip
- [x] : drool
- [x] : level
- [ ] : random dabs
## Music bot
- [ ] : play (WIP)
- [ ] : queue
- [ ] : np
- [ ] : pause
- [ ] : resume
- [ ] : skip
- [ ] : search
- [ ] : clear
- [ ] : pldump
## Misc
- [ ] : set <avatar|name|nick>
- [ ] : restart/shutdown
- [x] : exec
- [ ] : shitposting "^ interesting" and "hmm"
## Wishlist
- [ ] : nice-chess (we miss you saucy)
- [ ] : google image search (hi)
- [ ] : imagemagick
